- name: Configure EC2 Web Server
  hosts: web
  become: yes

  tasks:
    - name: Update packages
      yum:
        name: "*"
        state: latest

    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Start Apache
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Deploy sample HTML page
      copy:
        src: ./app/index.html
        dest: /var/www/html/index.html
