pipeline {
    agent any

    environment {
        TERRAFORM_BIN = "${WORKSPACE}/terraform/terraform"
        AWS_ACCESS_KEY_ID     = credentials('aws-access-key')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key')
        AWS_DEFAULT_REGION     = "ap-south-1"
        PATH = "${env.PATH}:${WORKSPACE}/terraform"
    }

    stages {

        stage('Checkout SCM') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/utkarshapatilU/Terraform-Task.git',
                    credentialsId: 'github-creds'
            }
        }

        stage("Install Terraform") {
            steps {
                echo "Downloading Terraform..."
                sh '''
                    set -x
                    wget -q https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip
                    unzip -o terraform_1.9.8_linux_amd64.zip

                    mkdir -p ${WORKSPACE}/terraform
                    mv terraform ${WORKSPACE}/terraform/terraform
                    chmod +x ${WORKSPACE}/terraform/terraform
                '''
            }
        }

        stage("Terraform Init") {
            steps {
                sh '''
                    cd terraform
                    ${TERRAFORM_BIN} init
                '''
            }
        }

        stage("Terraform Validate") {
            steps {
                sh '''
                    cd terraform
                    ${TERRAFORM_BIN} validate
                '''
            }
        }

        stage("Terraform Plan") {
            steps {
                sh '''
                    cd terraform
                    ${TERRAFORM_BIN} plan
                '''
            }
        }

        stage("Terraform Apply") {
            when {
                branch "main"
            }
            steps {
                sh '''
                    cd terraform
                    ${TERRAFORM_BIN} apply -auto-approve
                '''
            }
        }
    }

    post {
        failure {
            echo "Pipeline failed! Check logs."
        }
        success {
            echo "Pipeline completed successfully!"
        }
    }
}
